apiVersion: v1
kind: Service
metadata:
  name: llama3-api-service
  namespace: synapse # <-- ADD THIS
spec:
  selector:
    app: llama3-api
  ports:
    - protocol: TCP
      port: 8002
      targetPort: 8002
  type: ClusterIP